// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID            pgtype.UUID
	Name          string
	Description   pgtype.Text
	EmployeeCount int32
	Registered    bool
	Type          string
}
