name: dev

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0

      - name: Run golangci-lint
        run: |
          golangci-lint run --config .golangci.yml

  build-and-test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Verify dependencies
        run: |
          go mod verify

      - name: Build
        run: |
          go build -o ./bin/app ./cmd

      - name: Test
        run: |
          go test -v ./...